export const CREATE_CHANNEL_REQUEST = "CREATE_CHANNEL_REQUEST";
export const CREATE_CHANNEL_SUCCESS = "CREATE_CHANNEL_SUCCESS";
export const CREATE_CHANNEL_FAIL = "CREATE_CHANNEL_FAIL";

export const STAR_CHANNEL_REQUEST = "STAR_CHANNEL_REQUEST";
export const STAR_CHANNEL_SUCCESS = "STAR_CHANNEL_SUCCESS";
export const STAR_CHANNEL_FAIL = "STAR_CHANNEL_FAIL";

export const UNSTAR_CHANNEL_REQUEST = "UNSTAR_CHANNEL_REQUEST";
export const UNSTAR_CHANNEL_SUCCESS = "UNSTAR_CHANNEL_SUCCESS";
export const UNSTAR_CHANNEL_FAIL = "UNSTAR_CHANNEL_FAIL";

export const GET_CHANNELS_REQUEST = "GET_CHANNELS_REQUEST";
export const GET_CHANNELS_SUCCESS = "GET_CHANNELS_SUCCESS";
export const GET_CHANNELS_FAIL = "GET_CHANNELS_FAIL";
export const GET_CHANNELS_CLEAR = "GET_CHANNELS_CLEAR";

export const GET_STARRED_CHANNELS_REQUEST = "GET_STARRED_CHANNELS_REQUEST";
export const GET_STARRED_CHANNELS_SUCCESS = "GET_STARRED_CHANNELS_SUCCESS";
export const GET_STARRED_CHANNELS_FAIL = "GET_STARRED_CHANNELS_FAIL";
export const GET_STARRED_CHANNELS_CLEAR = "GET_STARRED_CHANNELS_CLEAR";

export const GET_CURRENT_CHANNEL_REQUEST = "GET_CURRENT_CHANNEL_REQUEST";
export const GET_CURRENT_CHANNEL_SUCCESS = "GET_CURRENT_CHANNEL_SUCCESS";
export const GET_CURRENT_CHANNEL_FAIL = "GET_CURRENT_CHANNEL_FAIL";
export const GET_CURRENT_CHANNEL_SET_PRIVATE =
  "GET_CURRENT_CHANNEL_SET_PRIVATE";
export const GET_CURRENT_CHANNEL_SET_PUBLIC = "GET_CURRENT_CHANNEL_SET_PUBLIC";
export const GET_CURRENT_CHANNEL_CLEAR = "GET_CURRENT_CHANNEL_CLEAR";
