export const CREATE_MESSAGE_REQUEST = "CREATE_MESSAGE_REQUEST";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAIL = "CREATE_MESSAGE_FAIL";

export const GET_MESSAGES_FROM_CHANNEL_REQUEST =
  "GET_MESSAGES_FROM_CHANNEL_REQUEST";
export const GET_MESSAGES_FROM_CHANNEL_SUCCESS =
  "GET_MESSAGES_FROM_CHANNEL_SUCCESS";
export const GET_MESSAGES_FROM_CHANNEL_FAIL = "GET_MESSAGES_FROM_CHANNEL_FAIL";
export const GET_MESSAGES_FROM_CHANNEL_CLEAR =
  "GET_MESSAGES_FROM_CHANNEL_CLEAR";
